### ISSUE TITLE
TypeError: Not JSON Serializable what's wrong? please help me!

### ISSUE THREAD

**Issue by JACKYLUO1991** [xiaochus/MobileNetV3#5]

**Comment by fzyzcjy** [comment]
The Lambda layer should be pulled out from the object, I also had that problem

**Comment by fzyzcjy** [comment]
I may make a PR tomorrow😂

**Comment by JACKYLUO1991** [comment]
@fzyzcjy thanks, i have solved it...

**Comment by xiaochus** [comment]
@actionLUO @fzyzcjy Could you provide detail of this error？I didn't see it in my local test.

**Comment by fzyzcjy** [comment]
@xiaochus on my mobile phone now so cannot give code. main idea: when saving model chkpt to disk, lambda layer have error

**Comment by JACKYLUO1991** [comment]
Lambda has error. u can simply convert it to other coding format...

**Comment by xiaochus** [comment]
@actionLUO @actionLUO For custom layers you should save_weights(), not save(), this what i did in the model. I can save weights file and load weights file without any error, did you modify the save part?
