### ISSUE TITLE
Missing activation layer after DepthwiseConv2D in the bottleneck layer 

### ISSUE THREAD

**Issue by VincentChong123** [xiaochus/MobileNetV3#6]
Thanks for sharing your code!

Compared to attached image from [Searching for MobileNetV3](https://arxiv.org/abs/1905.02244?context=cs), an activation layer (NL) after DepthwiseConv2D seems to be missing from your code below. The code is extracted from _bottleneck() in mobilenet_base.py.

```

        x = DepthwiseConv2D(kernel, strides=(s, s), depth_multiplier=1, padding='same')(x)
        x = BatchNormalization(axis=channel_axis)(x)
        
        if squeeze:
            x = Lambda(lambda x: x * self._squeeze(x))(x)
```

![ScreenHunter_123 May  25 14 27](https://user-images.githubusercontent.com/17609244/58365588-32751080-7ef9-11e9-9a47-1a9562391fbc.jpg)

**Comment by xiaochus** [comment]
@weishengchong Thanks for your correction! I put activation function after squeeze module and i will fix it.
